LPS-85855 TrashIndexer tests
luanmaoski/liferay-portal pull request #17
Opened 2019-01-18 17:11 UTC by luanmaoski

2019-01-18 17:11 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2019-01-18 17:11 UTC, luanmaoski commented
ci:test:search

2019-01-18 17:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest(master)/3597/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3597/jenkins-report.html">here</a>.</b></p>

2019-01-18 18:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 12 out of 16 jobs passed in 1 hour 29 minutes 21 seconds 504 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bd688f3693ae9135edc26008adb8681049896dad">bd688f3693ae9135edc26008adb8681049896dad</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/e264d18d74927dc0c3fb41228119e82ca272e0b8">e264d18d74927dc0c3fb41228119e82ca272e0b8</a></p>12 out of 16 jobs PASSED<div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest(master)/3597/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/273620/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/134781/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282725/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/213782/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/273619/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/213783/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/134780/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282724/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284369/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/213784/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/136375/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/136376/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287529/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250596/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270442/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3597/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/273620/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>18 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/273620//consoleText">AXIS_VARIABLE=1,label_exp=!master #273620</a><ol><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/273620//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDeletedWebContent_">LocalFile.Search#SearchDeletedWebContent</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1547831574197/test-portal-acceptance-pullrequest(master)/3597/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1547831574197/test-portal-acceptance-pullrequest(master)/3597/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1547831574197/test-portal-acceptance-pullrequest(master)/3597/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/273620//consoleText">AXIS_VARIABLE=2,label_exp=!master #273620</a><ol><li><div><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/273620//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_ViewStagedAndLiveContentInSearchResults_">LocalFile.Search#ViewStagedAndLiveContentInSearchResults</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1547831574197/test-portal-acceptance-pullrequest(master)/3597/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1547831574197/test-portal-acceptance-pullrequest(master)/3597/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-5/1547831574197/test-portal-acceptance-pullrequest(master)/3597/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282725/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/282725//consoleText">AXIS_VARIABLE=1,label_exp=!master #282725</a><pre><code>    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1642)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    [junit] 	at org.eclipse.osgi.framework.eventmgr.EventManager.di [...]

2019-01-21 13:07 UTC, luanmaoski commented
ci:test:search

2019-01-21 13:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/3172/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3172/jenkins-report.html">here</a>.</b></p>

2019-01-21 13:12 UTC, ifnazar requested changes

2019-01-21 13:12 UTC, ifnazar commented on modules/apps/trash/trash-test/src/testIntegration/java/com/liferay/trash/search/test/TrashFixture.java
> +		catch (PortalException pe) {
you can remove this catch, you do not use

2019-01-21 13:12 UTC, ifnazar commented on modules/apps/trash/trash-test/src/testIntegration/java/com/liferay/trash/search/test/TrashIndexerSearchTest.java
> +				_fileEntry.getFileEntryId());
you do not need to get the object again

2019-01-21 14:28 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 11 out of 16 jobs passed in 1 hour 21 minutes 23 seconds 926 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a6fc07ea7c25e8a23b9e4a8b469f7e7866e926c6">a6fc07ea7c25e8a23b9e4a8b469f7e7866e926c6</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/a11342eacf7c74ed039cdfaef340e7cac9c9ebf5">a11342eacf7c74ed039cdfaef340e7cac9c9ebf5</a></p>11 out of 16 jobs PASSED<div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/3172/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270740/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271626/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</strong></strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/263897/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229218/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</strong></strike></a></li></ul></div><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287849/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262641/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/136747/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250778/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250779/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/136748/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287851/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274747/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274748/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25862/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262642/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3172/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270740/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>18 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/270740//consoleText">AXIS_VARIABLE=1,label_exp=!master #270740</a><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/270740//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDeletedWebContent_">LocalFile.Search#SearchDeletedWebContent</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548076084417/test-portal-acceptance-pullrequest(master)/3172/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548076084417/test-portal-acceptance-pullrequest(master)/3172/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548076084417/test-portal-acceptance-pullrequest(master)/3172/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/270740//consoleText">AXIS_VARIABLE=2,label_exp=!master #270740</a><ol><li><div><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/270740//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_ViewStagedAndLiveContentInSearchResults_">LocalFile.Search#ViewStagedAndLiveContentInSearchResults</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548076084417/test-portal-acceptance-pullrequest(master)/3172/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548076084417/test-portal-acceptance-pullrequest(master)/3172/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548076084417/test-portal-acceptance-pullrequest(master)/3172/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/263897/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/263897//consoleText">AXIS_VARIABLE=1,label_exp=!master #263897</a><pre><code>    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:999)
    [junit] 	at org [...]

2019-01-21 16:10 UTC, luanmaoski commented
ci:test:search

2019-01-21 16:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/3175/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3175/jenkins-report.html">here</a>.</b></p>

2019-01-21 17:27 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 12 out of 16 jobs passed in 1 hour 16 minutes 6 seconds 237 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e1226e17f999a491a3669f1c5b8577be8fbc7703">e1226e17f999a491a3669f1c5b8577be8fbc7703</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/08659419788f85c26062b077f07901cd0e74e799">08659419788f85c26062b077f07901cd0e74e799</a></p>12 out of 16 jobs PASSED<div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/3175/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229230/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/186158/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282963/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</strong></strike></a></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/252331/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271259/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/263929/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270773/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287883/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/135250/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287884/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/185886/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282962/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250809/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/252332/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282964/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3175/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/229230/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>18 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/229230//consoleText">AXIS_VARIABLE=1,label_exp=!master #229230</a><ol><li><div><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/229230//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDeletedWebContent_">LocalFile.Search#SearchDeletedWebContent</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548087049745/test-portal-acceptance-pullrequest(master)/3175/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548087049745/test-portal-acceptance-pullrequest(master)/3175/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548087049745/test-portal-acceptance-pullrequest(master)/3175/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/229230//consoleText">AXIS_VARIABLE=2,label_exp=!master #229230</a><ol><li><div><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/229230//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_ViewStagedAndLiveContentInSearchResults_">LocalFile.Search#ViewStagedAndLiveContentInSearchResults</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548087049745/test-portal-acceptance-pullrequest(master)/3175/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548087049745/test-portal-acceptance-pullrequest(master)/3175/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1548087049745/test-portal-acceptance-pullrequest(master)/3175/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/186158/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/186158//consoleText">AXIS_VARIABLE=1,label_exp=!master #186158</a><pre><code>    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:999)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop [...]

2019-01-21 17:35 UTC, luanmaoski commented
ci:test:search

2019-01-21 17:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/3224/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-21.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3224/jenkins-report.html">here</a>.</b></p>

2019-01-21 19:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 12 out of 16 jobs passed in 1 hour 34 minutes 50 seconds 398 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e1226e17f999a491a3669f1c5b8577be8fbc7703">e1226e17f999a491a3669f1c5b8577be8fbc7703</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/08659419788f85c26062b077f07901cd0e74e799">08659419788f85c26062b077f07901cd0e74e799</a></p>12 out of 16 jobs PASSED<div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest(master)/3224/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250832/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250833/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284693/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</strong></strike></a></li></ul></div><details><summary><strong>12 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274098/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262717/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274099/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/135274/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262718/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262719/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/135275/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274100/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274101/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25896/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25897/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/25898/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3224/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250832/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>18 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/250832//consoleText">AXIS_VARIABLE=1,label_exp=!master #250832</a><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/250832//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDeletedWebContent_">LocalFile.Search#SearchDeletedWebContent</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-21/1548092164838/test-portal-acceptance-pullrequest(master)/3224/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-21/1548092164838/test-portal-acceptance-pullrequest(master)/3224/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-21/1548092164838/test-portal-acceptance-pullrequest(master)/3224/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/250832//consoleText">AXIS_VARIABLE=2,label_exp=!master #250832</a><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/250832//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_ViewStagedAndLiveContentInSearchResults_">LocalFile.Search#ViewStagedAndLiveContentInSearchResults</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-21/1548092164838/test-portal-acceptance-pullrequest(master)/3224/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-21/1548092164838/test-portal-acceptance-pullrequest(master)/3224/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-21/1548092164838/test-portal-acceptance-pullrequest(master)/3224/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250833/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/250833//consoleText">AXIS_VARIABLE=1,label_exp=!master #250833</a><pre><code>    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:999)
    [junit] 	at org.apache.catalina.util.LifecycleBase. [...]

2019-01-22 10:38 UTC, luanmaoski commented on modules/apps/trash/trash-test/src/testIntegration/java/com/liferay/trash/search/test/TrashIndexerSearchTest.java
> +				_fileEntry.getFileEntryId());
I need. I am using the `path` field here: `Assert.assertEquals(searchTerm, document.get("path"));`, this field changes when the file is moved to the trash.

2019-01-22 10:38 UTC, luanmaoski commented on modules/apps/trash/trash-test/src/testIntegration/java/com/liferay/trash/search/test/TrashFixture.java
> +		catch (PortalException pe) {
Alright.

2019-01-22 10:38 UTC, luanmaoski commented
ci:test:search

2019-01-22 10:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/4316/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4316/jenkins-report.html">here</a>.</b></p>

2019-01-22 12:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 14 out of 17 jobs passed in 1 hour 33 minutes 29 seconds 634 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9946390de501d5ad71ef8ba1d1f8011cbd20837">d9946390de501d5ad71ef8ba1d1f8011cbd20837</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/08659419788f85c26062b077f07901cd0e74e799">08659419788f85c26062b077f07901cd0e74e799</a></p>14 out of 17 jobs PASSED<div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/4316/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250954/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271432/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>14 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/264103/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/242287/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270944/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274905/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270945/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/135487/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/262886/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284813/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/186013/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284814/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/186014/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284815/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250955/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/135489/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4316/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/250954/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>18 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/250954//consoleText">AXIS_VARIABLE=1,label_exp=!master #250954</a><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/250954//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDeletedWebContent_">LocalFile.Search#SearchDeletedWebContent</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1548153537798/test-portal-acceptance-pullrequest(master)/4316/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1548153537798/test-portal-acceptance-pullrequest(master)/4316/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1548153537798/test-portal-acceptance-pullrequest(master)/4316/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/250954//consoleText">AXIS_VARIABLE=2,label_exp=!master #250954</a><ol><li><div><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/250954//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_ViewStagedAndLiveContentInSearchResults_">LocalFile.Search#ViewStagedAndLiveContentInSearchResults</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1548153537798/test-portal-acceptance-pullrequest(master)/4316/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1548153537798/test-portal-acceptance-pullrequest(master)/4316/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-11/1548153537798/test-portal-acceptance-pullrequest(master)/4316/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271432/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/271432//consoleText">AXIS_VARIABLE=0,label_exp=!master #271432</a><ol><li><div><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/271432//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">PortalLogAssertorTest.testScanXMLLog</a><pre>< [...]

2019-01-23 15:09 UTC, luanmaoski commented
ci:test:search

2019-01-23 15:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/4013/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4013/jenkins-report.html">here</a>.</b></p>

2019-01-23 17:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 14 out of 17 jobs passed in 1 hour 31 minutes 57 seconds 388 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a016eaebaa07c2dfb81ceaf91909a97475cb4352">a016eaebaa07c2dfb81ceaf91909a97475cb4352</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/7dd5ea1a45e070ff2d854e1071c70191a761fc97">7dd5ea1a45e070ff2d854e1071c70191a761fc97</a></p>14 out of 17 jobs PASSED<div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/4013/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/137538/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/264603/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>14 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/137537/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271863/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274902/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271864/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274903/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/137539/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274904/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271865/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/271866/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/274905/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/136048/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/263331/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/214496/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/136049/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4013/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/137538/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>18 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/137538//consoleText">AXIS_VARIABLE=1,label_exp=!master #137538</a><ol><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/137538//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_SearchDeletedWebContent_">LocalFile.Search#SearchDeletedWebContent</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-2/1548257945797/test-portal-acceptance-pullrequest(master)/4013/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-2/1548257945797/test-portal-acceptance-pullrequest(master)/4013/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.Search_SearchDeletedWebContent/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-2/1548257945797/test-portal-acceptance-pullrequest(master)/4013/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/137538//consoleText">AXIS_VARIABLE=2,label_exp=!master #137538</a><ol><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/137538//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Search_ViewStagedAndLiveContentInSearchResults_">LocalFile.Search#ViewStagedAndLiveContentInSearchResults</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-2/1548257945797/test-portal-acceptance-pullrequest(master)/4013/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-2/1548257945797/test-portal-acceptance-pullrequest(master)/4013/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.Search_ViewStagedAndLiveContentInSearchResults/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-2/1548257945797/test-portal-acceptance-pullrequest(master)/4013/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li><li><div><h5><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/264603/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/264603//consoleText">AXIS_VARIABLE=0,label_exp=!master #264603</a><ol><li><div><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/264603//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog">PortalLogAssertorTest.testScanXMLLog</a></div></li [...]

2019-02-15 12:45 UTC, luanmaoski commented
ci:test:search

2019-02-15 12:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest(master)/3781/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3781/jenkins-report.html">here</a>.</b></p>

2019-02-15 14:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 16 out of 18 jobs passed in 1 hour 48 minutes 28 seconds 912 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c763449ad99aedbf55e78543f25f78118092638b">c763449ad99aedbf55e78543f25f78118092638b</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/d0360aa7fab4bc625fa2bf8f2c423eeef04c094a">d0360aa7fab4bc625fa2bf8f2c423eeef04c094a</a></p>16 out of 18 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest(master)/3781/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/143582/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>16 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/269157/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/293768/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/255860/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282033/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/277130/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270603/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/232978/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/219739/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/293769/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/232979/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287825/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/9</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/219740/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/269158/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/189680/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/287826/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/276834/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3781/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/143582/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>2 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/143582//consoleText">AXIS_VARIABLE=2,label_exp=!master #143582</a><pre><code>    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:999)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1443)
    [junit] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1432)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:999)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:471)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:791)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.startup.Catalina.stop(Catalina.java:755)
    [junit] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:717)
    [junit] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
    [junit] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
    [junit] 
    [junit] 
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanOSGiLog(PortalLogAssertorTest.java:81)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.log.assertor.PortalLogAssertorTest FAILED
     [exec] Shutting down MySQL..[  OK  ]
     [echo] 
      [get] Getting: http://test-1-23/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/143582//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20190215135243065.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20190215135243065.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1717953258.properties</code></pre></div></li><li><div><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/143582//consoleText">AXIS_VARIABLE=6,label_exp=!master #143582</a><pre><code>    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at jav [...]

2019-02-15 14:39 UTC, luanmaoski commented
ci:test:search

2019-02-15 14:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/3847/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3847/jenkins-report.html">here</a>.</b></p>

2019-02-15 16:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search - 16 out of 18 jobs passed in 1 hour 24 minutes 31 seconds 728 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c763449ad99aedbf55e78543f25f78118092638b">c763449ad99aedbf55e78543f25f78118092638b</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/d0360aa7fab4bc625fa2bf8f2c423eeef04c094a">d0360aa7fab4bc625fa2bf8f2c423eeef04c094a</a></p>16 out of 18 jobs PASSED<div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/3847/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/291139/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li></ul></div><details><summary><strong>16 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/255893/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282107/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/293856/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/291138/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282108/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/31139/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/282109/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/255895/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/142472/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/276341/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/142473/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/9</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/255896/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/255897/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/270685/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/191464/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/276342/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3847/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/291139/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</a></h5><div><h6>Job Results:</h6><p>2 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/291139//consoleText">AXIS_VARIABLE=2,label_exp=!master #291139</a><pre><code>    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:999)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1443)
    [junit] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1432)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
    [junit] 	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:999)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:471)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:791)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
    [junit] 	at org.apache.catalina.startup.Catalina.stop(Catalina.java:755)
    [junit] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:717)
    [junit] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
    [junit] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
    [junit] 
    [junit] 
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanOSGiLog(PortalLogAssertorTest.java:81)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.log.assertor.PortalLogAssertorTest FAILED
     [exec] Shutting down MySQL..[  OK  ]
     [echo] 
      [get] Getting: http://test-1-20/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2,label_exp=!master/291139//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20190215153914508.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20190215153914508.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2121248310.properties</code></pre></div></li><li><div><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/291139//consoleText">AXIS_VARIABLE=6,label_exp=!master #291139</a><pre><code>    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    [junit] 	at ja [...]

2019-03-07 11:41 UTC, closed without merging